home_dir = './data/'
test_subdir = 'test_set/'
# train_subdir = 'train_set/'
train_subdir = 'test_set/'
val_subdir = 'test_set/'

hyperp ={
    "stage": "edge_classifier",
    "model": "InteractionGNN2",
    "input_dir": "/users/santoshp/standalone_IN_gnn/data/",
    "stage_dir": "/users/santoshp/standalone_IN_gnn/",
    "project": "Stand_alone",
    "gpus": 1,
    "nodes": 1,
    "data_split": [10, 5, 5],
    "dataset_class": "GraphDataset",
    "undirected": False,
    "weighting": [
        {"weight": 0.1, "conditions": {"y": False}},
        {"weight": 0.0, "conditions": {"y": True}},
        {
            "weight": 1.0,
            "conditions": {
                "y": True,
                "pt": [1000, float("inf")],
                "nhits": [3, float("inf")],
                "primary": True,
                "pdgId": ["not_in", [11, -11]],
                "radius": [0.0, 260.0],
                "eta_particle": [-4.0, 4.0],
                "redundant_split_edges": False,
            },
        },
    ],
    "edge_cut": 0.5,
    "node_features": [
        "r",
        "phi",
        "z",
        "eta",
        "cluster_r_1",
        "cluster_phi_1",
        "cluster_z_1",
        "cluster_eta_1",
        "cluster_r_2",
        "cluster_phi_2",
        "cluster_z_2",
        "cluster_eta_2",
    ],
    "node_scales": [
        1000.0,
        3.14159265359,
        1000.0,
        1.0,
        1000.0,
        3.14159265359,
        1000.0,
        1.0,
        1000.0,
        3.14159265359,
        1000.0,
        1.0,
    ],
    "edge_features": ["dr", "dphi", "dz", "deta", "phislope", "rphislope"],
    "hidden": 128,
    "n_graph_iters": 8,
    "n_node_encoder_layers": 3,
    "n_edge_encoder_layers": 3,
    "n_node_net_layers": 3,
    "n_edge_net_layers": 3,
    "n_node_decoder_layers": 3,
    "n_edge_decoder_layers": 3,
    "layernorm": False,
    "output_layer_norm": False,
    "edge_output_transform_final_layer_norm": False,
    "batchnorm": False,
    "output_batch_norm": False,
    "edge_output_transform_final_batch_norm": False,
    "bn_track_running_stats": False,
    "hidden_activation": "ReLU",
    "output_activation": "ReLU",
    "edge_output_transform_final_activation": None,
    "concat": True,
    "node_net_recurrent": False,
    "edge_net_recurrent": False,
    "in_out_diff_agg": True,
    "checkpointing": True,
    "warmup": 5,
    "lr": 0.0005,
    "min_lr": 0.000005,
    "factor": 0.9,
    "patience": 15,
    "max_epochs": 1,
    "max_training_graph_size": 2800000,
    "debug": False,
    "num_workers": [8, 8, 8],
}